# Generated by Django 2.2.16 on 2022-10-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20221022_1446'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_booking',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('author', 'user'), name='unique_follow'),
        ),
    ]
